### ISSUE TITLE
Request for Complete English Support for the Plugin

### ISSUE THREAD

**Issue by UsmanTechJive** [terwerinc/siyuan-plugin-share-pro#106]
I've tested the plugin, it looks great, quick and easy just like Notion. All I want to request is complete english support of the plugin.

![image](https://github.com/user-attachments/assets/690602bc-1e0e-4a08-9b18-c79efcb578fd)

![image](https://github.com/user-attachments/assets/db652f32-6c8e-4330-b68e-bcda4b3a35b5)

![image](https://github.com/user-attachments/assets/1a4eeb83-0d91-4a3b-a177-a153edeb86c8)

![image](https://github.com/user-attachments/assets/21a62b78-270e-4c07-bb8f-19c2238e20e3)

![image](https://github.com/user-attachments/assets/ba45d885-25f4-4643-834f-421d54655c2b)

![image](https://github.com/user-attachments/assets/acc0514d-2879-40a3-9dcd-e1ee58b00eb0)

![image](https://github.com/user-attachments/assets/ef5566f0-ee4f-422b-b7d4-0a458a7e8f30)

![image](https://github.com/user-attachments/assets/d83697ea-52b0-40a0-be7f-556fe5b59ded)

**Comment by terwer** [comment]
V1.5.0 have all i18n support for Enflish.
