### ISSUE TITLE
Add Support for Custom Domains

### ISSUE THREAD

**Issue by UsmanTechJive** [terwerinc/siyuan-plugin-share-pro#108]
I’d like to request the option to use our own custom domain as well as an option, so the final URL would look like this:

customdomain.com/documentEncryptedID

I already have a custom domain and would love to use it instead of siyuannote.space. This way, the link would appear more personalized if possible.

Also I prefer siyuannote.space better than siyuannote.site.

I will use both default domain and my domain for some documents.

**Comment by terwer** [comment]
It already supports custom, but only for paid user.
see https://github.com/terwerinc/siyuan-plugin-share-pro/issues/114
