### ISSUE TITLE
Feature Request: Add Hover-Activated Floating Outline for Improved Navigation like Capacities

### ISSUE THREAD

**Issue by UsmanTechJive** [terwerinc/siyuan-plugin-share-pro#110]
I think adding a floating outline on the right side, similar to what Capacities has, would be beneficial. When the user hovers over this area:

![image](https://github.com/user-attachments/assets/ce495a56-4a2e-4f71-b91b-3da5d05f2622)

The outline would appear, functioning properly and enhancing document navigation:

![image](https://github.com/user-attachments/assets/c4db5054-0cba-46c4-b3a0-01f9a96d946f)

Video for ref:

https://github.com/user-attachments/assets/653b1478-7d20-472c-a007-5d4c5d2fa7c8

**Comment by terwer** [comment]
Great idea, I am working on it hard.It will release at `11.10`

**Comment by UsmanTechJive** [comment]
Thanks, appreciated.

**Comment by UsmanTechJive** [comment]
Thanks, this is great! Just one thing: could you make the UI more modern like Capacities and with a hover effect? That would be fantastic.

**Comment by terwer** [comment]
> Thanks, this is great! Just one thing: could you make the UI more modern like Capacities and with a hover effect? That would be fantastic.

Thanks for your advice, I will try to improve it later.
