### ISSUE TITLE
自定义域名-Custom domain support

### ISSUE THREAD

**Issue by terwer** [terwerinc/siyuan-plugin-share-pro#114]
在线分享专业版支持自定义域名，收费用户如果想自定义域名，可以解析 dns 设置  CNAME
到 cname.vercel-dns.com 
然后联系我 youweics@163.com 添加
这样的话除了 siyuannote.site 和 siyuannote.space 你自己的 域名也能访问

Share pro supports custom domains. If paying users want to use a custom domain, they can set up DNS CNAME records to point to `cname.vercel-dns.com`. Then, contact me at `youweics@163.com` to add the domain. This way, in addition to `siyuannote.site` and `siyuannote.space`, your own domain can also be used to access the site

**Comment by UsmanTechJive** [comment]
It's great to hear that! I just have one more question: for each document a user uploads, will there be an option/choice to select the domain they want to use, such as siyuannote.site, siyuannote.space, or their own custom domain?

If that's the case then that would be great.

**Comment by terwer** [comment]
> It's great to hear that! I just have one more question: for each document a user uploads, will there be an option/choice to select the domain they want to use, such as siyuannote.site, siyuannote.space, or their own custom domain?
> 
> If that's the case then that would be great.

Both domains are available, if you mean the link when click view doc, a option will be add int the `Share Setting`, when set , the view link will just use your setting.Current it randoms from siyuannote.site and siyuannote.space.
